// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljnzwlzdzkwzftlehrlt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxqbnp3bHpkemt3emZ0bGVocmx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4Nzc3OTcsImV4cCI6MjA1NzQ1Mzc5N30.V1iAZzuDl9NbCzEdYLv6mc4drpCq5leunBwgGSxPKIQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);